# Generated by Django 5.1.3 on 2024-11-06 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='dara_horario',
            new_name='data_horario',
        ),
    ]
