# Generated by Django 5.1.3 on 2024-11-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_rename_dara_horario_agendamento_data_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_horario',
            field=models.DateTimeField(),
        ),
    ]
